config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :customers
  root 'customers#index'
  resources :comments, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :customers
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :company
  belongs_to :post
  has_many :comments
  
  validates :family_name, presence: true, length: { maximum: 20 }
  validates :given_name, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates :company_id, presence: true
  validates :post_id, presence: true
  
  def full_name
  family_name + given_name
  end

end

app/models/post.rb
class Post < ApplicationRecord
  has_many :customers

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery with: :exception
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:given_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:family_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:given_name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to @comment.customer
    else
      render template: "customer/show"
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @comment.customer
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:body, :customer_id)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_customer,only: [:show, :edit, :update, :destroy]
  def index
     @q = Customer.includes(:post, :company).ransack(params[:q])
    @customers = @q.result.page(params[:page])
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to @customer
    else
      render :new
    end
  end

  def edit
  
  end

  def update
    
    if  @customer.update(customer_params)
      redirect_to @customer
    else
      render :edit
    end
  end

  def show
    @comment = Comment.new
    @comments = @customer. comments
  end

  def destroy
    # データーを取得
    
    # データーを削除
    @customer.destroy
    # indexに戻る
    redirect_to customers_path
  end
  
  
  
  def customer_params
    params.require(:customer).permit(
      :family_name,
      :given_name,
      :email,
      :company_id,
      :post_id)
  end
  
  def set_customer
     @customer = Customer.find(params[:id])
  end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with model: @customer, local: true do |form| %>
  <% if @customer.errors.any? %>
    <div class="alert alert-danger">
      <p><b><%= @customer.errors.count %>件のエラーがあります</b></p>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :family_name %><br>
    <%= form.text_field :family_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :given_name %><br>
    <%= form.text_field :given_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :email %><br>
    <%= form.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :company_id %>
    <%= form.collection_select :company_id, Company.all, :id, :name , { include_blank: "会社を選択してください" },  { class: "form-control" } %>
  </div>
　<div class="form-group">
    <%= form.label :post_id %>
    <%= form.collection_select :post_id, Post.all, :id, :position_name, { include_blank: "役職を選択してください" }, { class: "form-control" } %>
  </div>
  <%= form.submit class: "btn btn-default" %>
<% end %>

app/views/customers/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>顧客情報の編集</h1>
    <%= render 'form' %>
    <button type="button" style="margin-top:5px;" class="btn btn-default" data-toggle="modal" data-target="#delete-customer">顧客情報を削除する</button>
    <%= link_to '戻る', customer_path(@customer),  style: "margin-top:5px;", class: "btn btn-default" %>
  </div>
</div>
<!-- 下記のモーダルは通常は隠れているので、どこに書いてもＯＫ -->
<div class="modal fade" id="delete-customer">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">顧客情報の削除</h4>
      </div>
      <div class="modal-body">
        <p><%= @customer.family_name %>さんを削除しますか？</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
        <%= link_to '削除する', @customer, method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/customers/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>顧客情報一覧</h1>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
    <p>お客様情報が表示されます。</p>
  </div>
  <div class="col-lg-6">
    <%= link_to '顧客登録', new_customer_path, class: "btn btn-default pull-right" %>
  </div>
  <%= search_form_for @q do |f| %>
    <div class="row">
      <div class="col-sm-3 col-xs-12">
        <div class="form-group">
          <%= f.label :family_name_cont, '姓' %>
          <%= f.search_field :family_name_cont, class: "form-control input-sm" %>
        </div>
      </div>
      <div class="col-sm-3 col-xs-12">
        <div class="form-group">
          <%= f.label :given_name_cont, '名' %>
          <%= f.search_field :given_name_cont, class: "form-control input-sm" %>
        </div>
      </div>
      <!-- 変更 col-sm-2 -->
      <div class="col-sm-2 col-xs-12">
        <div class="form-group">
          <%= f.label :email_cont, '電子メール' %>
          <%= f.search_field :email_cont, class: "form-control input-sm" %>
        </div>
      </div>
      <!-- 変更 col-sm-2 -->
      <div class="col-sm-2 col-xs-12">
        <div class="form-group">
          <%= f.label :company_name_cont, '会社名' %>
          <%= f.search_field :company_name_cont, class: "form-control input-sm" %>
        </div>
      </div>
      <!-- 追加 START -->
      <div class="col-sm-2 col-xs-12">
        <div class="form-group">
          <%= f.label :post_position_name_cont, '役職名' %>
          <%= f.search_field :post_position_name_cont, class: "form-control input-sm" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 text-center">
        <%= f.submit "検索", class: "btn btn-default" %>
        <%= link_to "リセット", request.path, class:"btn btn-default" %>
      </div>
    </div>
  <% end %>
  <hr />  
  <table class="table table-striped">
    <thead>
      <thead>
      <th><%= sort_link(@q, :family_name, "姓") %></th>
      <th><%= sort_link(@q, :given_name, "名") %></th>
      <th><%= sort_link(@q, :email, "電子メール") %></th>
      <th><%= sort_link(@q, :company_name, "所属会社") %></th>
      <th><%= sort_link(@q, :post_position_name, "役職") %></th>
    <th>リンク</th>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.family_name %></td>
          <td><%= customer.given_name %></td>
          <td><%= customer.email %></td>
          <td><%= customer.company.name %></td>
          <td><%= customer.post.position_name %></td> <!--追加 -->
          <td><%= link_to '詳細', customer, class: "btn btn-default btn-xs" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @customers %>
</div>

app/views/customers/new.html.erb
<div class="row">
  <div class="col-lg-12">
  <h1>顧客新規登録</h1>
  <%= render 'form' %>
  </div>    
</div>

app/views/customers/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>顧客詳細</h1>
    <dl>
      <dt>お名前</dt>
      <dd style="margin:0px 0px 10px 20px"><%= @customer.full_name %></dd>
      <dt>電子メール</dt>
      <dd style="margin:0px 0px 10px 20px"><%= @customer.email %></dd>
      <dt>会社名</dt>
      <dd style="margin:0px 0px 10px 20px"><%= @customer.company.name %></dd>
      <dt>役職名</dt>
      <dd style="margin:0px 0px 10px 20px"><%= @customer.post.position_name %></dd>
　　</dl>
    <%= link_to '編集', edit_customer_path(@customer), class: "btn btn-default" %>
    <%= link_to '戻る', customers_path, class: "btn btn-default" %>
    <hr>
    <h2>対応履歴</h2>
    <% @comments.each do |comment| %>
    <div class="media">
      <div class="media-body">
        <%= simple_format(comment.body) %>
        <p class="text-muted">
          投稿記事:<%= comment.created_at.strftime('%Y-%m-%d %H:%M')%>
          <%= link_to "削除する", comment_path(comment), method: :delete %>
        </p>
      </div>
    </div>
  <% end %>
    <hr/>

<!-- 下記を追加 -->
    <%= form_with model: @comment, url: { controller: :comments, action: :create } do |form| %>
      <div class="form-group">
        <%= form.label :body , '対応内容' %><br>
        <%= form.text_area :body, class: "form-control" %>
      </div>
      <%= form.hidden_field :customer_id, value: @customer.id %>
      <%= form.submit class: "btn btn-default" %>
    <% end %>

  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/customers">顧客管理システム</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-menu">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "設定変更", edit_user_registration_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpartaCrm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <div class="container">
       <% if notice.present? %>
        <div class="alert alert-dismissable alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <p><%= notice %></p>
        </div>
      <% end %>

      <% if alert.present? %>
        <div class="alert alert-dismissable alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <p><%= alert %></p>
        </div>
      <% end %>

    <%= yield %>
    </div>
  </body>
</html>